version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew build
  test:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: ./gradlew testDebugUnitTest
      - store_test_results:
          path: app/build/test-results

workflows:
  build-test:
    jobs:
      - build
      - test


#      - store_artifacts:
#          path: app/build/outputs/apk/debug/app-debug.apk
